export const PY_USD_ABI = [
	{
		type: "constructor",
		inputs: [
			{ name: "_mintToken", type: "address", internalType: "address" },
			{ name: "_minGiftAmount", type: "uint256", internalType: "uint256" },
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "allocateGift",
		inputs: [
			{ name: "wallets", type: "address[]", internalType: "address[]" },
			{ name: "amounts", type: "uint256[]", internalType: "uint256[]" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "approve",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "artistBalance",
		inputs: [{ name: "wallet", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "artistBalances",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "artists",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [
			{ name: "payoutWallet", type: "address", internalType: "address" },
			{ name: "name", type: "string", internalType: "string" },
			{ name: "imageURI", type: "string", internalType: "string" },
			{ name: "exists", type: "bool", internalType: "bool" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "balanceOf",
		inputs: [{ name: "owner", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "contractPYUSDBalance",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getApproved",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "isApprovedForAll",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
		],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "minGiftAmount",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "mint",
		inputs: [
			{ name: "wallet", type: "address", internalType: "address" },
			{ name: "amount", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "mintToken",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contractERC20" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "name",
		inputs: [],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "owner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "ownerOf",
		inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "owner", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "registerArtist",
		inputs: [
			{ name: "wallet", type: "address", internalType: "address" },
			{ name: "name", type: "string", internalType: "string" },
			{ name: "imageURI", type: "string", internalType: "string" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "safeTransferFrom",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "safeTransferFrom",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "uint256", internalType: "uint256" },
			{ name: "", type: "bytes", internalType: "bytes" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setApprovalForAll",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "bool", internalType: "bool" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "supportsInterface",
		inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "symbol",
		inputs: [],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "tokenAmounts",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "tokenArtist",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "tokenURI",
		inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalIssued",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "transferFrom",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "updateArtist",
		inputs: [
			{ name: "wallet", type: "address", internalType: "address" },
			{ name: "name", type: "string", internalType: "string" },
			{ name: "imageURI", type: "string", internalType: "string" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "withdrawForArtist",
		inputs: [
			{ name: "wallet", type: "address", internalType: "address" },
			{ name: "amount", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "Approval",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "spender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{ name: "id", type: "uint256", indexed: true, internalType: "uint256" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ApprovalForAll",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "operator",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{ name: "approved", type: "bool", indexed: false, internalType: "bool" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ArtistRegistered",
		inputs: [
			{
				name: "wallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{ name: "name", type: "string", indexed: false, internalType: "string" },
			{
				name: "imageURI",
				type: "string",
				indexed: false,
				internalType: "string",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ArtistUpdated",
		inputs: [
			{
				name: "wallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{ name: "name", type: "string", indexed: false, internalType: "string" },
			{
				name: "imageURI",
				type: "string",
				indexed: false,
				internalType: "string",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ArtistWithdrawn",
		inputs: [
			{
				name: "wallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "payoutWallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "GiftAllocated",
		inputs: [
			{
				name: "donor",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "totalAmount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "wallets",
				type: "address[]",
				indexed: false,
				internalType: "address[]",
			},
			{
				name: "amounts",
				type: "uint256[]",
				indexed: false,
				internalType: "uint256[]",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "GiftMinted",
		inputs: [
			{
				name: "tokenId",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "giver",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "wallet",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Transfer",
		inputs: [
			{ name: "from", type: "address", indexed: true, internalType: "address" },
			{ name: "to", type: "address", indexed: true, internalType: "address" },
			{ name: "id", type: "uint256", indexed: true, internalType: "uint256" },
		],
		anonymous: false,
	},
	{ type: "error", name: "ARTIST_EXISTS", inputs: [] },
	{ type: "error", name: "ARTIST_NOT_FOUND", inputs: [] },
	{ type: "error", name: "EMPTY_GIFT", inputs: [] },
	{ type: "error", name: "GIFT_TOO_LOW", inputs: [] },
	{ type: "error", name: "INSUFFICIENT_BALANCE", inputs: [] },
	{ type: "error", name: "INVALID_WALLET", inputs: [] },
	{ type: "error", name: "LENGTH_MISMATCH", inputs: [] },
	{ type: "error", name: "NOT_OWNER", inputs: [] },
	{ type: "error", name: "TRANSFERS_DISABLED", inputs: [] },
	{ type: "error", name: "UNAUTHORIZED", inputs: [] },
] as const;
